"""reset articles

Revision ID: 046e5436147c
Revises: 9008f6cab729
Create Date: 2020-10-01 12:16:38.672289

"""
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from alembic import op

# revision identifiers, used by Alembic.
revision = "046e5436147c"
down_revision = "9008f6cab729"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM link")
    op.execute("DELETE FROM article")
    articles_file: Path = Path(__file__).parent.parent / "articles_20201001.json"
    articles: List[Dict] = json.loads(articles_file.read_text())
    query = ""
    for article in articles:
        tags = json.dumps(article["tags"])
        created = datetime.fromisoformat(article["created"].replace("Z", "+00:00"))
        modified = datetime.fromisoformat(article["modified"].replace("Z", "+00:00"))
        intro = article["intro"].replace("'", "''")
        body = article["body"].replace("'", "''")
        title = article["title"].replace("'", "''")
        video = f"'{article['video']}'" if article["video"] else "NULL"
        query += f"""
INSERT INTO article
(uuid, created, modified, title, image, deleted, body, video, intro, tags)
VALUES
(
    '{article['uuid']}', '{created}', '{modified}', '{title}', '{article['image']}', NULL, 
    '{body}', {video}, '{intro}', '{tags}'
);
        """

        for link in article["links"]:
            link_created = datetime.fromisoformat(
                link["created"].replace("Z", "+00:00")
            )
            link_modified = datetime.fromisoformat(
                link["modified"].replace("Z", "+00:00")
            )
            link_intro = link["intro"].replace("'", "''")
            link_title = link["title"].replace("'", "''")
            query += f"""
INSERT INTO link
(uuid, created, modified, title, image, intro, article_id, deleted, url)
VALUES
('{link['uuid']}', '{link_created}', '{link_modified}', '{link_title}', '{link['image']}', '{link_intro}', '{article['uuid']}', NULL, '{link['url']}'
);
            """
    op.execute(query)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
