"""empty message

Revision ID: 67ebb1e3851f
Revises: c7428e16ddac
Create Date: 2018-03-23 11:41:40.213886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ebb1e3851f'
down_revision = 'c7428e16ddac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.Column('intro', sa.String(), nullable=False),
                    sa.Column('article_id', sa.String(), nullable=True),
                    sa.Column('deleted', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['article_id'], ['article.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
