"""empty message

Revision ID: 704b337fe8ee
Revises: a28decb66104
Create Date: 2018-02-06 15:39:34.072444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704b337fe8ee'
down_revision = 'a28decb66104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body', sa.String(), nullable=False))
    op.drop_column('article', 'description')
    op.add_column('tag', sa.Column('deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'deleted')
    op.add_column('article', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('article', 'body')
    # ### end Alembic commands ###
