"""empty message

Revision ID: a28decb66104
Revises: 
Create Date: 2018-02-06 11:19:56.161823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28decb66104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('deleted', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('uuid')
                    )
    op.create_table('tag',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('value')
                    )
    op.create_table('relationship_table',
                    sa.Column('article_id', sa.String(
                        length=36), nullable=False),
                    sa.Column('tag_id', sa.String(length=36), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['article_id'], ['article.uuid'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], ),
                    sa.PrimaryKeyConstraint('article_id', 'tag_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_table')
    op.drop_table('tag')
    op.drop_table('article')
    # ### end Alembic commands ###
