"""empty message

Revision ID: c7428e16ddac
Revises: f4c6a8ba308e
Create Date: 2018-02-09 15:25:28.947823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7428e16ddac'
down_revision = 'f4c6a8ba308e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('intro', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'intro')
    # ### end Alembic commands ###
