"""empty message

Revision ID: f4c6a8ba308e
Revises: 8bec8821bb03
Create Date: 2018-02-09 09:19:37.541419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c6a8ba308e'
down_revision = '8bec8821bb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.drop_table('relationship_table')
    op.add_column('article', sa.Column('video', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'video')
    op.create_table('relationship_table',
    sa.Column('article_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.uuid'], name='relationship_table_article_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], name='relationship_table_tag_id_fkey'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id', name='relationship_table_pkey')
    )
    op.drop_table('article_tag')
    # ### end Alembic commands ###
