x-environment:
  &COMMON_ENVIRONMENT
  ENVIRONMENT: DEVELOPMENT
  DATABASE_HOST: gdm-articles-api-db
  DATABASE_PORT: 5432
  DATABASE_USER: gdm-articles-api-db
  DATABASE_PASSWORD: gdm-articles-api-db
  DATABASE_NAME: gdm-articles-api-db
  CUSTOMER_CODE: DEV
  LOG_LEVEL: DEBUG
  LOG_FORMAT: COLOUR
  SERVER_TIMEZONE: Europe/London
  GDM_ARTICLES_WWW: "https://gdm-articles-api:5000"

services:
  gdm-articles-integration-tests:
    container_name: "gdm-articles-integration-tests"
    build:
      context: ./
      args:
        - PIP_EXTRA_INDEX_URL
    environment:
      <<: *COMMON_ENVIRONMENT
      BEHAVE_ARGS: ${BEHAVE_ARGS:-}
      REPORT_PORTAL_URL: ${REPORT_PORTAL_URL:-}
      REPORT_PORTAL_TOKEN: ${REPORT_PORTAL_TOKEN:-}
      REPORT_PORTAL_PROJECT: ${REPORT_PORTAL_PROJECT:-}
      ENVIRONMENT: ${ENVIRONMENT:-}
      RELEASE: ${RELEASE:-}
    command: >
      bash -c "behave --no-capture --no-logcapture ${BEHAVE_ARGS:-}"
    depends_on:
      "gdm-articles-api":
        condition: service_healthy

  gdm-articles-api:
    container_name: "gdm-articles-api"
    build:
      context: ..
      args:
        - GEMFURY_DOWNLOAD_KEY
    environment:
      <<: *COMMON_ENVIRONMENT
    command: >-
      bash -c "flask db upgrade && python -m gdm_articles_api"
    healthcheck:
      test: curl -f http://localhost:5000/running || false
      interval: 3s
      retries: 40
      start_period: 5s
    depends_on:
      "gdm-articles-api-db":
        condition: service_healthy

  gdm-articles-api-db:
    container_name: "gdm-articles-api-db"
    image: docker.io/postgres
    environment:
      POSTGRES_USER: gdm-articles-api-db
      POSTGRES_DB: gdm-articles-api-db
      POSTGRES_PASSWORD: gdm-articles-api-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 5s
